"""empty message

Revision ID: 080bd5b8367a
Revises: 150d0dd42cd2
Create Date: 2022-06-25 16:57:08.772395

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '080bd5b8367a'
down_revision = '150d0dd42cd2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Shows', sa.Column('venue_name', sa.String(), nullable=True))
    op.add_column('Shows', sa.Column('artist_name', sa.String(), nullable=True))
    op.add_column('Shows', sa.Column('artist_image_link', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Shows', 'artist_image_link')
    op.drop_column('Shows', 'artist_name')
    op.drop_column('Shows', 'venue_name')
    # ### end Alembic commands ###
