"""empty message

Revision ID: 9c604fa66c00
Revises: e690e6b42f0e
Create Date: 2022-06-12 21:25:08.195873

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c604fa66c00'
down_revision = 'e690e6b42f0e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('looking_for_venues', sa.Boolean(), nullable=True))
    op.add_column('Artist', sa.Column('upcoming_shows_count', sa.String(length=120), nullable=True))
    op.add_column('Artist', sa.Column('past_shows_count', sa.String(length=120), nullable=True))
    op.add_column('Artist', sa.Column('upcoming_shows', sa.String(length=500), nullable=True))
    op.add_column('Artist', sa.Column('past_shows', sa.String(length=500), nullable=True))
    op.add_column('Shows', sa.Column('start_time', sa.String(), nullable=True))
    op.add_column('Venue', sa.Column('upcoming_shows_count', sa.String(length=120), nullable=True))
    op.add_column('Venue', sa.Column('past_shows_count', sa.String(length=120), nullable=True))
    op.add_column('Venue', sa.Column('genres', sa.String(length=120), nullable=True))
    op.add_column('Venue', sa.Column('looking_for_talent', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Venue', 'looking_for_talent')
    op.drop_column('Venue', 'genres')
    op.drop_column('Venue', 'past_shows_count')
    op.drop_column('Venue', 'upcoming_shows_count')
    op.drop_column('Shows', 'start_time')
    op.drop_column('Artist', 'past_shows')
    op.drop_column('Artist', 'upcoming_shows')
    op.drop_column('Artist', 'past_shows_count')
    op.drop_column('Artist', 'upcoming_shows_count')
    op.drop_column('Artist', 'looking_for_venues')
    # ### end Alembic commands ###
