"""empty message

Revision ID: edea84666042
Revises: b0b52e29b810
Create Date: 2022-06-26 14:58:29.289637

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'edea84666042'
down_revision = 'b0b52e29b810'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Show', sa.Column('datetime', sa.DateTime(), nullable=False))
    op.drop_column('Show', 'start_time')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Show', sa.Column('start_time', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('Show', 'datetime')
    # ### end Alembic commands ###
